services:
    alttube-go:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8072:8072"
        volumes:
            - .env.docker:/app/.env
        container_name: alttube-go
        depends_on:
            - alttube-postgres
            - piped
            - piped-proxy
    alttube-postgres:
        image: postgres:alpine
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data
        container_name: alttube-postgres
    piped:
        image: 1337kavin/piped:latest
        restart: unless-stopped
        ports:
            - "8060:8080"
        volumes:
            - ./config.properties:/app/config.properties
        depends_on:
            - piped-postgres
        container_name: piped-backend
    piped-postgres:
        image: postgres:alpine
        restart: unless-stopped
        ports:
            - "8063:5432"
        volumes:
            - ./piped-data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=piped
            - POSTGRES_USER=piped
            - POSTGRES_PASSWORD=changeme
        container_name: piped-postgres
    piped-proxy:
        image: 1337kavin/piped-proxy:latest
        restart: unless-stopped
        ports:
            - "8061:8080"
        container_name: pipedproxy
