services:
    piped:
        image: 1337kavin/piped:latest
        restart: unless-stopped
        ports:
            - "8060:8080"
        volumes:
            - ./config.properties:/app/config.properties
        depends_on:
            - piped-postgres
        container_name: piped-backend
    piped-postgres:
        image: postgres:16-alpine
        restart: unless-stopped
        ports:
            - "8063:5432"
        volumes:
            - ./piped-data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=piped
            - POSTGRES_USER=piped
            - POSTGRES_PASSWORD=changeme
        container_name: piped-postgres
    pipedfrontend:
        image: 1337kavin/piped-frontend:latest
        restart: unless-stopped
        ports:
            - "8062:80"
        depends_on:
            - piped
        container_name: piped-frontend
        entrypoint: ash -c 'sed -i "s/https:\/\/pipedapi.kavin.rocks/http:\/\/localhost:8060/g" /usr/share/nginx/html/assets/* && /docker-entrypoint.sh && nginx -g "daemon off;"'
        environment:
            - BACKEND_HOSTNAME=localhost:8060
    piped-proxy:
        image: 1337kavin/piped-proxy:latest
        restart: unless-stopped
        ports:
            - "8061:8080"
        container_name: piped-proxy
