name: Auto-Approve Dependabot PRs

on:
  pull_request:
    types: [opened, synchronize]
  check_suite:
    types: [completed]

permissions:
  pull-requests: write
  checks: read

jobs:
  auto-approve:
    runs-on: ubuntu-latest

    steps:
      - name: Gather info via GitHub Script
        id: check
        uses: actions/github-script@v6
        with:
          script: |
            /**
             * 1. If event is pull_request:
             *    - Check if PR is from dependabot[bot].
             *    - Store pull_request.number in output for later usage.
             *
             * 2. If event is check_suite:
             *    - Check if check_suite.conclusion === 'success'.
             *    - Lookup any open PR(s) for the head_sha. 
             *      If the PR is from dependabot[bot], store that PR number in output.
             *
             * In either case, if conditions are not met, we set prNumber = 0 (no approval).
             */

            const eventName = context.eventName;

            let prNumber = 0; // default: no valid PR found
            let conclusion = null;

            if (eventName === 'pull_request') {
              const pr = context.payload.pull_request;
              if (pr.user.login === 'dependabot[bot]') {
                prNumber = pr.number;
              }
            } else if (eventName === 'check_suite') {
              conclusion = context.payload.check_suite.conclusion;
              if (conclusion === 'success') {
                const headSha = context.payload.check_suite.head_sha;
                
                // List pull requests for the commit (head SHA).
                const { data: pullRequests } = await github.repos.listPullRequestsAssociatedWithCommit({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  commit_sha: headSha
                });

                // If any open PR from dependabot exists for this SHA, pick it
                const dependabotPR = pullRequests.find(pr => 
                  pr.user.login === 'dependabot[bot]' && pr.state === 'open'
                );
                if (dependabotPR) {
                  prNumber = dependabotPR.number;
                }
              }
            }

            core.setOutput('prNumber', prNumber.toString());
          result-encoding: string

      - name: Approve PR if conditions are met
        if: ${{ steps.check.outputs.prNumber != '0' }}
        run: gh pr review --approve --repo "${{ github.repository }}" ${{ steps.check.outputs.prNumber }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
